# Generated by Django 2.0.2 on 2018-04-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Attendance',
            field=models.CharField(max_length=2),
        ),
    ]
